# Generated by Django 5.1.1 on 2024-10-31 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_images', models.IntegerField()),
                ('orientation', models.CharField(max_length=20)),
                ('auto_enhance', models.BooleanField(default=False)),
                ('compression', models.BooleanField(default=True)),
                ('pdf_size', models.IntegerField(help_text='Size in bytes')),
                ('status', models.CharField(max_length=20)),
                ('processing_time', models.FloatField(help_text='Time in seconds')),
            ],
            options={
                'verbose_name': 'PDF Conversion',
                'verbose_name_plural': 'PDF Conversions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size', models.IntegerField(default=10485760, help_text='Maximum file size in bytes')),
                ('max_images_per_conversion', models.IntegerField(default=20)),
                ('allowed_file_types', models.CharField(default='jpg,jpeg', max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('default_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('enable_compression', models.BooleanField(default=True)),
                ('enable_auto_enhance', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
