# Generated by Django 5.1.1 on 2024-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='allowed_file_types',
            field=models.CharField(default='jpg,jpeg,png', help_text='Comma separated file extensions (e.g., jpg,jpeg,png)', max_length=200),
        ),
    ]
